name: Run every 5 minutes

on:
  schedule:
    # 使用cron表达式，每5分钟执行一次
    - cron: "*/5 * * * *"

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      # 第一步：检查出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 第二步：设置Python环境（如果你的程序是Python程序）
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 第三步：安装依赖（根据你的程序需求修改）
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 第四步：运行你的程序
      - name: Run script
        run: |
          python your_script.py
